#!/bin/bash
STD="-std=gnu11"
WFLAGS="-Wall -pedantic"

#begin
if [[ "$1" = "--clean" ]] 
then
	echo "cleaning up"
	rm -f *.o *.out *.test junk* smallsh
elif [[ "$1" = "--ctags" ]]
then
	echo "Running 'ctags -R *'"
	ctags -R ./*
else
  #	
	# SIGDEBUG
	#
	if [[ "$1" = "--sigdebug" ]] 
	then
		echo "SIGDEBUG profile"
		SIGDBG="-DSIGDEBUG=1"
		DBGSYM="-ggdb3"
  #	
	# DEBUG
	#
	elif [[ "$1" = "--debug" ]] 
	then
		echo "DEBUG profile"
		DBGSYM="-ggdb3"
		DFLAG="-DDEBUG=1"
  #	
	# GDB
	#
	elif [[ "$1" = "--gdb" ]] 
	then
		echo "GBD profile"
		DBGSYM="-ggdb3"
  #	
	# PROD
	#
	else
		echo "PROD profile"
		OPTIM="-O3"	
	fi
	
	rm -f ./*.o
	rm -f ./smallsh 
	
	gcc $STD $OPTIM	$WFLAGS $DBGSYM -I. $SIGDBG $DFLAG -c cmdstruct.c
	gcc $STD $OPTIM	$WFLAGS $DBGSYM -I. $SIGDBG $DFLAG -c smshbuiltin.c
	gcc $STD $OPTIM	$WFLAGS $DBGSYM -I. $SIGDBG $DFLAG -c smshchild.c
	gcc $STD $OPTIM	$WFLAGS $DBGSYM -I. $SIGDBG $DFLAG -c smshregex.c
	gcc $STD $OPTIM	$WFLAGS $DBGSYM -I. $SIGDBG $DFLAG -c smshsignals.c

	echo STD: "$STD"
	echo WFLAGS: "$WFLAGS"
	echo DBGSYM: "$DBGSYM"
	echo SIGDBG: "$SIGDBG"
	echo DFLAG: "$DFLAG"
	echo OPTIM: "$OPTIM"
	#echo "gcc $STD $OPTIM $WFLAGS $DBGSYM $DFLAG $SIGDBG -I. -o smallsh ./smshchild.o ./smshsignals.o\
		#./smshbuiltin.o ./smshregex.o ./cmdstruct.o ./smallsh.c"
	
	gcc $STD $OPTIM $WFLAGS $DBGSYM $DFLAG $SIGDBG -I. -o smallsh ./smshchild.o ./smshsignals.o ./smshbuiltin.o ./smshregex.o ./cmdstruct.o ./smallsh.c

	if [[ "$1" = "-g" ]]
	then
		if [[ "$2" = "-x" ]]
			then
				gdb ./smallsh
		fi
	fi

fi #end
