#!/bin/bash
STD="-std=gnu11"
if [[ ($1 = DEBUG) ]] 
then
	echo "DEBUG profile"
	rm -f ./*.o
	rm -f ./smallsh 
	gcc $STD -Wall -pedantic -DDEBUG=1 -ggdb3 -I. -c cmdstruct.c
	gcc $STD -Wall -pedantic -DDEBUG=1 -ggdb3 -I. -c smshsignals.c
	gcc $STD -Wall -pedantic -DDEBUG=1 -ggdb3 -I. -c smshregex.c
	gcc $STD -Wall -pedantic -DDEBUG=1 -ggdb3 -I. -c smshbuiltin.c
	gcc $STD -Wall -pedantic -DDEBUG=1 -ggdb3 -I. -o smallsh ./smshsignals.o ./smshbuiltin.o ./smshregex.o ./cmdstruct.o ./smallsh.c
elif [[ $1 = "PROD" ]]
then
	echo "PROD profile"
	rm -f ./smallsh 
	gcc -std=c11 -Wall -pedantic -o smallsh ./cmdstruct.h ./smallsh.c
fi
