#!/usr/bin/env bash
DFLAG=""

if [[ "$1" == '-c' ]]
then
	echo "CLEAN"
	rm -f keygen
	rm -f ./*.o
fi

if [[ "$1" == '-t' ]]
then
	echo "CTAGS/CSCOPE"
	ctags -R ./*
	cscope -R -b
fi

if [[ "$1" == '-g' ]]
then
	echo "DEBUG"
	DFLAG="-DDEBUG"
	rm -f ./*.o keygen	
	gcc -std=gnu11 $DFLAG -Og -g3 -Wall -pedantic -I. -o keygen.c
	#gcc -std=gnu11 $DFLAG -Og -g3 -Wall -pedantic -I. -o ftserver ftserver.c
fi

if [[ "$#" -eq 0 ]]
then
	rm -f ./*.o keygen	
	gcc -std=gnu11 -O3 -Wall -pedantic -I. -o keygen keygen.c
	#gcc -std=gnu11 -O3 -Wall -pedantic -I. -o ftserver ftserver.c
fi

