#!/usr/bin/env bash
DFLAGS=""
OFLAG=""

if [[ "$1" == '-c' ]]
then
	echo "CLEAN"
	rm -f ./*.o keygen otp_enc otp_enc_d
	exit 0
fi

if [[ "$1" == '-t' ]]
then
	echo "CTAGS/CSCOPE"
	ctags -R ./*
	cscope -R -b
	exit 0
fi

if [[ "$1" == '-g' ]]
then
	echo "DEBUG"
	DFLAGS="-DDEBUG=1 -g3"
	OFLAG="-Og"
	#gcc -std=gnu11 $DFLAG -Og -g3 -Wall -pedantic -I. -o keygen keygen.c
	#gcc -std=gnu11 $DFLAG -Og -g3 -Wall -pedantic -I. -c srvr_common.c
	#gcc -std=gnu11 $DFLAG -Og -g3 -Wall -pedantic -I. srvr_common.o -o otp_enc_d otp_enc_d.c
fi

gcc -std=gnu11 $OFLAG $DFLAGS -Wall -pedantic -I. -o keygen keygen.c
gcc -std=gnu11 $OFLAG $DFLAGS -Wall -pedantic -I. -c srvr_common.c
gcc -std=gnu11 $OFLAG $DFLAGS -Wall -pedantic -I. -c clnt_common.c
gcc -std=gnu11 $OFLAG $DFLAGS -Wall -pedantic -I. clnt_common.o -o otp_enc otp_enc.c
gcc -std=gnu11 $OFLAG $DFLAGS -Wall -pedantic -I. srvr_common.o -o otp_enc_d otp_enc_d.c 
gcc -std=gnu11 $OFLAG $DFLAGS -Wall -pedantic -I. clnt_common.o -o otp_dec otp_dec.c
gcc -std=gnu11 $OFLAG $DFLAGS -Wall -pedantic -I. srvr_common.o -o otp_dec_d otp_dec_d.c 

