#!/bin/bash
#cannot use math library
#gcc -ansi -lm -Wall -pedantic -g -o boettchc.buildrooms ./boettchc.buildrooms.c
if [[ $1 = "DEBUG" ]]
then
	gcc -Wall -DDEBUG=1 -ggdb3 -o boettchc.buildrooms ./boettchc.buildrooms.c
	gcc -Wall -DDEBUG=1 -ggdb3 -o boettchc.adventure ./boettchc.adventure.c -lpthread
elif [[ $1 = "PROD" ]]
then
	gcc -o boettchc.buildrooms ./boettchc.buildrooms.c 
	gcc -o boettchc.adventure ./boettchc.adventure.c -lpthread
fi
